# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c298ac2b027acff7dc7fc06e040762fc2dd7aeeabb0f14bdf7c514fcdf6d2f1061d62498c57742bb17c5ac4ddfe440cf59bc0269b0ac7b0688ae37244c003c08

test:
  secret_key_base: e6a6170d030d015451fd0821b2730ce534fbd47fa8768467bf39c6ced80ef4690c7bb9e76c996d91411114645e9bd9858f86fb02cadf9440b6722f20d0f56b68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
